#SPDX-License-Identifier: MIT-0
---
# defaults file for ansible-role-vault

vault_working_dir: /vault

vault_image_name: hashicorp/vault:latest
vault_container_name: vault
vault_restart_policy: always

vault_token_id: dev-only-token
vault_address: http://0.0.0.0:8200
vault_host_port: 8200

vault_backend_file_name: "{{ vault_working_dir }}/file"
vault_default_lease_ttl: 168h
vault_max_lease_ttl: 0h