#SPDX-License-Identifier: MIT-0
---

- name: vault | create vault base directory
  ansible.builtin.file:
    path: "{{ vault_working_dir }}"
    state: directory

- name: vault | copy docker-compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ vault_working_dir }}/docker-compose.yml"

- name: vault | run service
  ansible.builtin.command: docker compose up -d
  args:
    chdir: "{{ vault_working_dir }}"
