#SPDX-License-Identifier: MIT-0
---

- name: vault | run vault
  ansible.builtin.include_tasks: run.yml

- name: sleep a little until vault is ready to accept connections
  ansible.builtin.pause:
    seconds: 40

- name: vault | run vault
  ansible.builtin.include_tasks: init.yml
