- name: vault | create vault base directory
  ansible.builtin.file:
    path: "{{ vault_working_dir }}"
    state: directory

- name: vault | copy docker-compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ vault_working_dir }}/docker-compose.yml"
  notify:
    vault | restart docker

- name: vault | copy vault config template
  ansible.builtin.template:
    src: vault-config.json.j2
    dest: "{{ vault_working_dir }}/{{ __vault_config_name }}"
  notify:
    vault | restart docker

- name: vault | run service
  ansible.builtin.command: docker compose up -d
  args:
    chdir: "{{ vault_working_dir }}"